# Refer to https://github.com/probe-rs/cargo-embed/blob/master/src/config/default.toml
# for the comprehensive list of options

[default.probe]
protocol = "Swd"
speed = 1500 # ref: openocd: target/stm32l4x.cfg

[default.general]
chip = "STM32L442KCTx"

[default.flashing]
do_chip_erase = false
enabled = false

[default.rtt]
enabled = true
show_timestamps = true
channels = [
    # How to enable Defmt formatting (https://github.com/knurling-rs/defmt)
    # (formats on host, not on microcontroller)?
    # microcontroller setup: https://github.com/knurling-rs/app-template
    { up = 0, name = "log", format = "Defmt" },
]

[default.gdb]
enabled = true
gdb_connection_string = "127.0.0.1:2331"