[package]
authors = ["ololoshka2871"]
edition = "2018"
readme = "README.md"
name = "stm32-usb-self-writer"
version = "0.2.0"

[dependencies]
num = { version = "0.4", default-features = false, features = ["alloc"] }
num-derive = "0.3"
num-traits = { version = "0.2", default-features = false }
static_assertions = "1.1.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
embedded-hal = "0.2.4"
cortex-m = "0.7.3"
cortex-m-rt = "0.6.11" # need by stm32l4 == 0.13.0
#freertos-rust = "0.1.2"
freertos-rust = { git = "https://github.com/lobaro/FreeRTOS-rust.git" }

stm32l4xx-hal = { version= "0.6.0", features = ["rt"] }

serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

usb-device = "0.2.7"
stm32-usbd = "0.6.0"
usbd-serial = { path = "lib/usbd-serial" }
usbd_scsi = { path = "lib/stm32-usb.rs/firmware/usbd_scsi", features = ["no-zlp"] }
usbd_mass_storage = "0.1.0"

# defmt
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2", features = ["print-defmt"] }

heatshrink-rust = { path = "lib/heatshrink-rust" }
emfat-rust = { path = "lib/emfat" }
nanopb-rs = { path = "lib/nanopb.rs/nanopb-rs" }
flash-settings-rs = { path = "lib/flash-settings.rs" }
my-proc-macro = { path = "lib/my-proc-macro" }

[build-dependencies]
cc = "1.0.52"
freertos-cargo-build = "0.1.1"
nanopb-rs-generator = { path = "lib/nanopb.rs/nanopb-rs-generator" }

[profile.dev.package."*"]
opt-level = "z"

[profile.dev]
opt-level = "z"
lto = false
panic = "abort"

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[features]
default = [
   "defmt-default", # отключить когда собираешь релиз
   "monitor-heap",
   "stm32l433",
 ]

 monitor-heap = []
 stm32l433 = [ "stm32l4xx-hal/stm32l4x2" ]

 # do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
