# usage: https://github.com/sagiegurari/cargo-make

[env]
#executable={script=["cargo run --bin 2>&1 > /dev/null | tail -n2 | sed -e 's/^ *//;s/ *$//' -e '/^$/d'"]}
path="target/thumbv6m-none-eabi/debug"
executable = { script = ["find ${path} -maxdepth 1 -type f ! -name \"*.*\""] }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

##############

[tasks.openocd]
command = "openocd"
args = [
    "-f",
    "openocd.cfg",
]

##############

[tasks.f]
command = "arm-none-eabi-gdb"
args = ["-x", "flash.gdb"]
dependencies = ["build"]

##############

[tasks.fr]
command = "arm-none-eabi-gdb"
args = ["-x", "flashr.gdb"]
dependencies = ["build"]
